import { PrismaClient, Category } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.$transaction(async (tx) => {
    // Limpieza previa (orden de dependencias)
    await tx.quote.deleteMany();
    await tx.customer.deleteMany();
    await tx.product.deleteMany();
    await tx.categories.deleteMany();

    // ── Categorías ─────────────────────────────────────────────────────────
    await tx.categories.createMany({
      data: [
        { name: "Micrófonos", enum: "MICROPHONES" },
        { name: "Mezcladores", enum: "MIXERS" },
        { name: "Sistemas PA", enum: "PAS" },
        { name: "Equipos DJ", enum: "DJ" },
        { name: "Audífonos", enum: "HEADPHONES" },
        { name: "Cables", enum: "CABLES" },
        { name: "Accesorios", enum: "ACCESOSORIES" },
      ],
    });

    // ── Productos ───────────────────────────────────────────────────────────
    await tx.product.createMany({
      data: [
        // ── MICRÓFONOS ────────────────────────────────────────────────────
        {
          name: "AKG C214 Stereo Pair",
          brand: "AKG",
          price: 30.0,
          weight: 1200,
          stock: 1,
          specs: "Condenser cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Beyerdynamic OPUS99",
          brand: "Beyerdynamic",
          price: 7.86,
          weight: 0,
          stock: 1,
          specs: "Kick cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Rode K2",
          brand: "Rode",
          price: 29.29,
          weight: 820,
          stock: 1,
          specs: "Diafragma grande valvular",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser e815",
          brand: "Sennheiser",
          price: 5.0,
          weight: 0,
          stock: 1,
          specs: "Cardioide con switch",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser Micrófonos Corbateros",
          brand: "Sennheiser",
          price: 214.29,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser e-609 Silver",
          brand: "Sennheiser",
          price: 5.71,
          weight: 140,
          stock: 1,
          specs: "Dinámico cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser e614",
          brand: "Sennheiser",
          price: 12.14,
          weight: 0,
          stock: 1,
          specs: "Condenser hipercardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser e-845",
          brand: "Sennheiser",
          price: 5.71,
          weight: 0,
          stock: 1,
          specs: "Dinámico cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser e-906",
          brand: "Sennheiser",
          price: 6.43,
          weight: 0,
          stock: 1,
          specs: "Dinámico cardioide con filtro",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser e-914",
          brand: "Sennheiser",
          price: 14.29,
          weight: 0,
          stock: 1,
          specs: "Condenser cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser MD-421",
          brand: "Sennheiser",
          price: 13.57,
          weight: 0,
          stock: 1,
          specs: "Dinámico cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser MD-441",
          brand: "Sennheiser",
          price: 34.29,
          weight: 0,
          stock: 1,
          specs: "Dinámico cardioide con filtro",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Shure Beta 57A",
          brand: "Shure",
          price: 5.71,
          weight: 0,
          stock: 1,
          specs: "Dinámico cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Shure Beta 87A",
          brand: "Shure",
          price: 10.71,
          weight: 0,
          stock: 1,
          specs: "Condenser hipercardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Shure PG 52",
          brand: "Shure",
          price: 5.71,
          weight: 0,
          stock: 1,
          specs: "Dinámico cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Shure PG 56",
          brand: "Shure",
          price: 5.71,
          weight: 0,
          stock: 1,
          specs: "Dinámico cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Shure PG Drum Kit",
          brand: "Shure",
          price: 25.0,
          weight: 0,
          stock: 1,
          specs: "Kit de micrófonos para batería",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Shure SE 215",
          brand: "Shure",
          price: 2.0,
          weight: 0,
          stock: 1,
          specs: "Micrófono in ear",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Shure SM57",
          brand: "Shure",
          price: 5.71,
          weight: 280,
          stock: 1,
          specs: "Dinámico cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Shure SM58",
          brand: "Shure",
          price: 5.71,
          weight: 300,
          stock: 1,
          specs: "Dinámico cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "SKP VHF 665",
          brand: "SKP",
          price: 4.29,
          weight: 0,
          stock: 1,
          specs: "Wireless dinámico de mano",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Sennheiser EW 135G2 Wireless",
          brand: "Sennheiser",
          price: 14.29,
          weight: 0,
          stock: 1,
          specs: "Wireless cardioide",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Receptor Shure BLX + SM58",
          brand: "Shure",
          price: 28.57,
          weight: 0,
          stock: 1,
          specs: "Sistema wireless SM58",
          description: "",
          category: Category.MICROPHONES,
        },
        {
          name: "Audio Technica M2T UHF Stereo Transmitter",
          brand: "Audio Technica",
          price: 11.79,
          weight: 0,
          stock: 1,
          specs: "Base para transmisión de auriculares in ear",
          description: "",
          category: Category.MICROPHONES,
        },

        // ── MEZCLADORES ───────────────────────────────────────────────────
        {
          name: "Allen & Heath ZED-6",
          brand: "Allen & Heath",
          price: 1.75,
          weight: 0,
          stock: 1,
          specs: "Analógica 6 canales",
          description: "",
          category: Category.MIXERS,
        },
        {
          name: "Midas F-24",
          brand: "Midas",
          price: 35.0,
          weight: 0,
          stock: 1,
          specs: "Analógica 24 canales",
          description: "",
          category: Category.MIXERS,
        },
        {
          name: "Midas MR18",
          brand: "Midas",
          price: 28.57,
          weight: 0,
          stock: 1,
          specs: "Digital 18CH IN / 4 AUX",
          description: "",
          category: Category.MIXERS,
        },
        {
          name: "Wharfedale Pro 1002 FX",
          brand: "Wharfedale Pro",
          price: 3.57,
          weight: 0,
          stock: 1,
          specs: "Analógica 6 canales",
          description: "",
          category: Category.MIXERS,
        },
        {
          name: "Yamaha 01V96VCM",
          brand: "Yamaha",
          price: 27.86,
          weight: 0,
          stock: 1,
          specs: "Digital 32 canales",
          description: "",
          category: Category.MIXERS,
        },
        {
          name: "Yamaha MG102C",
          brand: "Yamaha",
          price: 7.14,
          weight: 0,
          stock: 1,
          specs: "Analógica 10 canales",
          description: "",
          category: Category.MIXERS,
        },
        {
          name: "Yamaha MG206-C",
          brand: "Yamaha",
          price: 10.71,
          weight: 0,
          stock: 1,
          specs: "Analógica 20 canales",
          description: "",
          category: Category.MIXERS,
        },

        // ── SISTEMAS PA ───────────────────────────────────────────────────
        {
          name: "Phonic SEM712",
          brand: "Phonic",
          price: 6.07,
          weight: 0,
          stock: 1,
          specs: '150W RMS, 12", pasivo',
          description: "",
          category: Category.PAS,
        },
        {
          name: "Phonic SEM712A",
          brand: "Phonic",
          price: 8.57,
          weight: 0,
          stock: 1,
          specs: '150W RMS, 12", activo',
          description: "",
          category: Category.PAS,
        },
        {
          name: "RCF 325",
          brand: "RCF",
          price: 26.07,
          weight: 0,
          stock: 1,
          specs: '400W RMS, 15", activo',
          description: "",
          category: Category.PAS,
        },
        {
          name: "RCF Art 322A",
          brand: "RCF",
          price: 27.14,
          weight: 0,
          stock: 1,
          specs: '400W RMS, 12", activo',
          description: "",
          category: Category.PAS,
        },
        {
          name: "RCF Art 525",
          brand: "RCF",
          price: 35.71,
          weight: 0,
          stock: 1,
          specs: '750W RMS, 15", activo',
          description: "",
          category: Category.PAS,
        },
        {
          name: "Subwoofer RCF 4pro 8003-AS",
          brand: "RCF",
          price: 53.57,
          weight: 0,
          stock: 1,
          specs: '1000W RMS, 18", activo',
          description: "",
          category: Category.PAS,
        },
        {
          name: "Subwoofer Samson DB1500a",
          brand: "Samson",
          price: 21.43,
          weight: 0,
          stock: 1,
          specs: '500W RMS, 15", activo',
          description: "",
          category: Category.PAS,
        },
        {
          name: "Yamaha MSR250",
          brand: "Yamaha",
          price: 21.43,
          weight: 0,
          stock: 1,
          specs: '200W RMS, 10", activo',
          description: "",
          category: Category.PAS,
        },
        {
          name: "Yamaha MSR400",
          brand: "Yamaha",
          price: 27.14,
          weight: 0,
          stock: 1,
          specs: '400W RMS, 15", activo',
          description: "",
          category: Category.PAS,
        },

        // ── EQUIPOS DJ ────────────────────────────────────────────────────
        {
          name: "Allen & Heath Xone Controller",
          brand: "Allen & Heath",
          price: 1.5,
          weight: 0,
          stock: 1,
          specs: "Controlador DJ",
          description: "",
          category: Category.DJ,
        },

        // ── AUDÍFONOS ─────────────────────────────────────────────────────
        {
          name: "Sennheiser HD 202",
          brand: "Sennheiser",
          price: 10.71,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.HEADPHONES,
        },

        // ── CABLES ────────────────────────────────────────────────────────
        {
          name: "Cable Alargue Power",
          brand: "Genérico",
          price: 2.14,
          weight: 0,
          stock: 1,
          specs: "Hasta 15 metros",
          description: "",
          category: Category.CABLES,
        },
        {
          name: "Cable XLR / TRS / TS",
          brand: "Genérico",
          price: 2.86,
          weight: 0,
          stock: 1,
          specs: "Hasta 11 metros",
          description: "",
          category: Category.CABLES,
        },
        {
          name: "Cable Interlock 220v",
          brand: "Genérico",
          price: 1.07,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.CABLES,
        },
        {
          name: "Cable UTP 50 metros",
          brand: "Genérico",
          price: 7.86,
          weight: 0,
          stock: 1,
          specs: "50 metros, jacks hembra",
          description: "",
          category: Category.CABLES,
        },
        {
          name: "Patchera Escenario PROEL 24x8",
          brand: "Proel",
          price: 17.14,
          weight: 0,
          stock: 1,
          specs: "24 IN x 8 OUT, 30 mts",
          description: "",
          category: Category.CABLES,
        },
        {
          name: "Patchera Escenario PROEL 16x4",
          brand: "Proel",
          price: 13.57,
          weight: 0,
          stock: 1,
          specs: "16 IN x 4 OUT, 20 mts",
          description: "",
          category: Category.CABLES,
        },
        {
          name: "Zapatilla Eléctrica 220v",
          brand: "Genérico",
          price: 1.43,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.CABLES,
        },

        // ── ACCESORIOS ────────────────────────────────────────────────────
        {
          name: "Behringer Microamp HA400",
          brand: "Behringer",
          price: 2.5,
          weight: 0,
          stock: 1,
          specs: "Amplificador de auriculares, 4 canales",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Presonus HP4",
          brand: "Presonus",
          price: 16.43,
          weight: 0,
          stock: 1,
          specs: "Amplificador de auriculares, 4 canales",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Apple iPad",
          brand: "Apple",
          price: 18.57,
          weight: 0,
          stock: 1,
          specs: "Tablet para operar wireless",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Batería Acústica Ludwig Classic Star 1969",
          brand: "Ludwig",
          price: 142.86,
          weight: 0,
          stock: 1,
          specs: "White Sparkle",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Presonus Digimax 8",
          brand: "Presonus",
          price: 7.14,
          weight: 0,
          stock: 1,
          specs: "8 preamps con ADAT",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Focusrite Scarlett 18i20",
          brand: "Focusrite",
          price: 46.43,
          weight: 0,
          stock: 1,
          specs: "Interfaz de audio, 2da generación",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Rupert Neve 542 Tape Emulator",
          brand: "Rupert Neve",
          price: 0.54,
          weight: 0,
          stock: 1,
          specs: "Procesador serie 500",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Alesis Pico Verb",
          brand: "Alesis",
          price: 2.5,
          weight: 0,
          stock: 1,
          specs: "Procesador de efectos/reverb",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Behringer Feedback Destroyer FBQ-2496",
          brand: "Behringer",
          price: 2.36,
          weight: 0,
          stock: 1,
          specs: "Destructor de feedback automático",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "ART Pro VLA II",
          brand: "ART",
          price: 2.5,
          weight: 0,
          stock: 1,
          specs: "Compresor",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Empirical Labs Deeser",
          brand: "Empirical Labs",
          price: 0.39,
          weight: 0,
          stock: 1,
          specs: "Procesador serie 500",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "DBX DriveRack",
          brand: "DBX",
          price: 0.46,
          weight: 0,
          stock: 1,
          specs: "Crossover, EQ, compresor y limitador",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Kush Electra EQ S500",
          brand: "Kush Audio",
          price: 0.5,
          weight: 0,
          stock: 1,
          specs: "EQ paramétrico serie 500",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Lexicon MX400",
          brand: "Lexicon",
          price: 10.71,
          weight: 0,
          stock: 1,
          specs: "Procesador reverb/delay/chorus",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "DBX 560 Limiter/Compressor",
          brand: "DBX",
          price: 0.18,
          weight: 0,
          stock: 1,
          specs: "Procesador serie 500",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "GoPro",
          brand: "GoPro",
          price: 3.57,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Zoom H1n",
          brand: "Zoom",
          price: 14.29,
          weight: 0,
          stock: 1,
          specs: "Grabadora portátil",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Inclinadores de Bafle 30°",
          brand: "Genérico",
          price: 0.07,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "LunchBox 500 Series 11 Slots",
          brand: "Ovie",
          price: 0.43,
          weight: 0,
          stock: 1,
          specs: "Rack serie 500, 11 slots",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Pie de Bafle Alto",
          brand: "Genérico",
          price: 4.29,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Pie de Bafle Chico",
          brand: "Genérico",
          price: 3.57,
          weight: 0,
          stock: 1,
          specs: "Cajas hasta 10 pulgadas",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Pie de Bafle Mediano",
          brand: "Genérico",
          price: 3.93,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Pie de Micrófono Hercules",
          brand: "Hercules",
          price: 0.36,
          weight: 0,
          stock: 1,
          specs: "Trípode pesado",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Pie de Micrófono",
          brand: "Genérico",
          price: 3.21,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: 'MacBook Pro 13"',
          brand: "Apple",
          price: 28.57,
          weight: 0,
          stock: 1,
          specs: "Retina, 256GB SSD",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Caja Directa Behringer Stereo",
          brand: "Behringer",
          price: 3.21,
          weight: 0,
          stock: 1,
          specs: "Activa stereo",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Caja Directa DBX",
          brand: "DBX",
          price: 3.93,
          weight: 0,
          stock: 1,
          specs: "Pasiva",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Caja Directa Radioshack",
          brand: "Radioshack",
          price: 2.5,
          weight: 0,
          stock: 1,
          specs: "Pasiva sin thru",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Caja Directa Samson",
          brand: "Samson",
          price: 3.21,
          weight: 0,
          stock: 1,
          specs: "Activa con PAD y GRND Lift",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Router WiFi",
          brand: "Genérico",
          price: 3.57,
          weight: 0,
          stock: 1,
          specs: "",
          description: "",
          category: Category.ACCESOSORIES,
        },
        {
          name: "Universal Audio Apollo Twin Quad",
          brand: "Universal Audio",
          price: 14.29,
          weight: 0,
          stock: 1,
          specs: "Interfaz de audio",
          description: "",
          category: Category.ACCESOSORIES,
        },
      ],
    });
  });

  console.log("✅ Seed completado exitosamente");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
